-- Phase A Pro content types
ALTER TYPE "QrContentType" ADD VALUE IF NOT EXISTS 'VCARD';
ALTER TYPE "QrContentType" ADD VALUE IF NOT EXISTS 'COUPON';
ALTER TYPE "QrContentType" ADD VALUE IF NOT EXISTS 'LOCATION';
ALTER TYPE "QrContentType" ADD VALUE IF NOT EXISTS 'EMAIL';
ALTER TYPE "QrContentType" ADD VALUE IF NOT EXISTS 'SMS';
