-- Phase B Pro content types
ALTER TYPE "QrContentType" ADD VALUE IF NOT EXISTS 'APP_LINK';
ALTER TYPE "QrContentType" ADD VALUE IF NOT EXISTS 'VIDEO';
ALTER TYPE "QrContentType" ADD VALUE IF NOT EXISTS 'AUDIO';
ALTER TYPE "QrContentType" ADD VALUE IF NOT EXISTS 'EVENT';
